config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  get 'pages/cabinet'
  get 'pages/conseils'
  get 'pages/contact'
  get 'pages/drgrard'
  get 'pages/services'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def cabinet
  end

  def conseils
  end

  def contact
  end

  def drgrard
  end

  def services
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>Dr Valery Grard Chirurgien-Dentiste</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="shortcut icon" type="image/x-icon" href="../assets/favicon.ico" />
    <link rel="stylesheet" href="../assets/plugins/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="../assets/plugins/icofont/icofont.css">
    <link rel="stylesheet" href="../assets/plugins/slick-carousel/slick/slick.css">
    <link rel="stylesheet" href="../assets/plugins/slick-carousel/slick/slick-theme.css">
    <link rel="stylesheet" href="../assets/style.css">
  </head>

  <body>
    <%= render 'shared/navbar'%>
    <%= yield %>
    <%= render 'shared/footer'%>
  </body>

  <script src="../assets/plugins/jquery/jquery.js"></script>
  <script src="../assets/plugins/bootstrap/js/popper.js"></script>
  <script src="../assets/plugins/bootstrap/js/bootstrap.min.js"></script>
  <script src="../assets/plugins/counterup/jquery.easing.js"></script>
  <script src="../assets/plugins/slick-carousel/slick/slick.min.js"></script>
  <script src="../assets/plugins/counterup/jquery.waypoints.min.js"></script>
  <script src="../assets/plugins/shuffle/shuffle.min.js"></script>
  <script src="../assets/plugins/counterup/jquery.counterup.min.js"></script>
  <script src="../assets/plugins/google-map/map.js"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAkeLMlsiwzp6b3Gnaxd86lvakimwGA6UA&callback=initMap"></script>
  <script src="../assets/script.js"></script>
  <script src="../assets/contact.js"></script>

</html>

app/views/pages/cabinet.html.erb
<section class="page-title bg-1">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="block text-center">
          <span class="text-white">Dr GRARD Valéry, chirurgien-dentiste</span>
          <h1 class="text-capitalize mb-5 text-lg">Notre cabinet</h1>

          <!-- <ul class="list-inline breadcumb-nav">
            <li class="list-inline-item"><a href="index.html" class="text-white">Home</a></li>
            <li class="list-inline-item"><span class="text-white">/</span></li>
            <li class="list-inline-item"><a href="#" class="text-white-50">All Department</a></li>
          </ul> -->
        </div>
      </div>
    </div>
  </div>
</section>
<br>
<br>

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="4"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="5"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="6"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="7"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="8"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="../assets/cabinet1" style="max-height:500px; width:auto; display: block; margin-left: auto;
margin-right: auto;" class="d-block " alt="...">
    </div>
    <div class="carousel-item">
      <img src="../assets/cabinet2" style="max-height:500px; width:auto; display: block; margin-left: auto;
margin-right: auto;" class="d-block" alt="...">
    </div>
    <div class="carousel-item">
      <img src="../assets/cabinet3" style="max-height:500px; width:auto; display: block; margin-left: auto;
margin-right: auto;" class="d-block" alt="...">
    </div>
    <div class="carousel-item">
      <img src="../assets/cabinet4" style="max-height:500px; width:auto; display: block; margin-left: auto;
margin-right: auto;" class="d-block" alt="...">
    </div>
    <div class="carousel-item">
      <img src="../assets/cabinet5" style="max-height:500px; width:auto; display: block; margin-left: auto;
margin-right: auto;" class="d-block" alt="...">
    </div>
    <div class="carousel-item">
      <img src="../assets/cabinet6" style="max-height:500px; width:auto; display: block; margin-left: auto;
margin-right: auto;" class="d-block" alt="...">
    </div>
    <div class="carousel-item">
      <img src="../assets/cabinet7" style="max-height:500px; width:auto; display: block; margin-left: auto;
margin-right: auto;" class="d-block" alt="...">
    </div>
    <div class="carousel-item">
      <img src="../assets/cabinet8" style="max-height:500px; width:auto; display: block; margin-left: auto;
margin-right: auto;" class="d-block" alt="...">
    </div>
    <div class="carousel-item">
      <img src="../assets/cabinet9" style="max-height:500px; width:auto; display: block; margin-left: auto;
margin-right: auto;" class="d-block" alt="...">
    </div>
  </div>

</div>

<section class="section about-page">
  <div class="container">
    <div class="row">
      <div class="col-lg-4">
        <h2 class="title-color">Bienvenue dans notre cabinet dentaire</h2>
      </div>
      <div class="col-lg-8">
        <p>Le Docteur GRARD, chirurgien-dentiste à Cavalaire, proche de St Tropez et Lavandou, est heureuse de vous accueillir sur le site Internet de son cabinet.<br>

 La dentisterie moderne, et les progrès de la profession permettent au Dr GRARD de vous accompagner quotidiennement pour une bonne hygiène dentaire, des soins spécifiques en implantologie, parfaitement adaptés avec le souci permanent de la meilleure esthétique dentaire.<br>



Le docteur GRARD pratique  une Dentisterie générale et plus particulierement la parodontologie, l'implantologie et la chirurgie buccale. Par ailleurs, nous assurons vos soins en Endodontie, vos eclaircissements de dents au cabinet, mais aussi  la pose de prothèses fixes et amovibles.</p>
        <img src="images/about/sign.png" alt="" class="img-fluid">
      </div>
    </div>
  </div>
</section>


<section class="section testimonial">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 offset-lg-6">
        <div class="section-title">
          <h2 class="mb-4">L'esprit de notre cabinet</h2>
          <div class="divider  my-4"></div>
        </div>
      </div>
    </div>
    <div class="row align-items-center">
      <div class="col-lg-6 testimonial-wrap offset-lg-6">

        <div class="testimonial-block">
          <div class="client-info ">

            <h4>Un plateau technique moderne</h4>

          </div>
          <p>
            Nous sommes là pour vous conseiller le meilleur de la technologie éprouvée et approuvée scientifiquement , un traitement personnalisé le plus simple et le moins onéreux possible tout en vous apportant le meilleur des pronostics.
          </p>
          <i class="icofont-quote-right"></i>

        </div>

        <div class="testimonial-block">
          <div class="client-info ">
            <h4>Un service personnalisé</h4>

          </div>
          <p>
            Parce que chaque cas est différent votre première visite nous permettra de trouver la solution personnalisée et de vous proposer immédiatement les examens complémentaires nécessaires à l'établissement d un plan de traitement et d'un devis.
          <i class="icofont-quote-right"></i>

        </div>


        <div class="testimonial-block">
          <div class="client-info">
            <h4>Une approche conservatrice</h4>

          </div>
          <p>
            Notre but est de vous garder un maximum de dents naturelles sur l'arcade : vos dents si elles sont fonctionnelles vous permettent de garder 'une proprioception' c'est-à-dire de sentir réellement ce que vous mastiquez.


          </p>
          <i class="icofont-quote-right"></i>
        </div>

        <div class="testimonial-block">
          <div class="client-info">
            <h4>Une dentisterie raisonnée</h4>

          </div>
          <p>
            Extraire toutes vos dents pour les remplacer par des implants n'est pas la solution idéale ! Elle doit être réservée aux cas extrêmes où aucune dent ne peut être fonctionnelle sur l'arcade. Les nouvelles techniques sauvent plus de dents !


          </p>
          <i class="icofont-quote-right"></i>
        </div>


        <div class="testimonial-block">
          <div class="client-info">
            <h4>Des soins sans douleur</h4>

          </div>
          <p>
            Chaque acte thérapeutique pouvant entrainer une douleur est effectuée sous anesthésie locale.
Un traitement post-opératoire vous permettra de ne pas avoir mal après votre soin.
<br>
<br>
          </p>
          <i class="icofont-quote-right"></i>
        </div>



        <div class="testimonial-block">
          <div class="client-info">
            <h4>Une disponibilité sans faille</h4>

          </div>
          <p>
            Dans le cadre de votre traitement et quelque soit votre souci, nous sommes joignables et vous recevrons en urgence si besoin est.
            <br>
            <br>
            <br>
          </p>
          <i class="icofont-quote-right"></i>
        </div>

        <div class="testimonial-block">
          <div class="client-info">
            <h4>Une totale transparence</h4>

          </div>
          <p>
            Nos tarifs se situent dans la moyenne nationale et un devis vous est remis pour tout acte le nécessitant.
            <br>
            <br>
            <br>
            <br>
          </p>
          <i class="icofont-quote-right"></i>
        </div>

      </div>
    </div>
  </div>
</section>




<section class="section team">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-6">
        <div class="section-title text-center">
          <h2 class="mb-4">L'équipe "garder le sourire"</h2>
          <div class="divider mx-auto my-4"></div>
          <p>Une équipe complète et motivée pour une prise en charge optimale</p>
        </div>
      </div>
    </div>

    <div class="row">

      <div class="col-lg-3 col-md-6 col-sm-6">
        <div class="team-block mb-5 mb-lg-0">
          <img src="../assets/AvatarValery.png" alt="" class="img-fluid w-100">

          <div class="content">
            <h4 class="mt-4 mb-0"><a href="doctor-single.html">Dr GRARD Valéry</a></h4>
            <p>Chirurgien-dentiste</p>
          </div>
        </div>
      </div>

      <div class="col-lg-3 col-md-6 col-sm-6">
        <div class="team-block mb-5 mb-lg-0">
          <img src="../assets/avatarcollaboratrice.png" alt="" class="img-fluid w-100">

          <div class="content">
            <h4 class="mt-4 mb-0"><a href="doctor-single.html">Christelle</a></h4>
            <p>Collaboratrice</p>
          </div>
        </div>
      </div>

      <div class="col-lg-3 col-md-6 col-sm-6">
        <div class="team-block mb-5 mb-lg-0">
          <img src="../assets/avatarcollaboratrice.png" alt="" class="img-fluid w-100">

          <div class="content">
            <h4 class="mt-4 mb-0"><a href="doctor-single.html">Virginie</a></h4>
            <p>Collaboratrice</p>
          </div>
        </div>
      </div>

      <div class="col-lg-3 col-md-6 col-sm-6">
        <div class="team-block mb-5 mb-lg-0">
          <img src="../assets/avatarcollaboratrice.png" alt="" class="img-fluid w-100">

          <div class="content">
            <h4 class="mt-4 mb-0"><a href="doctor-single.html">Johanna</a></h4>
            <p>Collaboratrice</p>
          </div>
        </div>
      </div>

    </div>
  </div>
</section>


<section class="contact-form-wrap section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-10">
                <div class="section-title text-center">
                    <h2 class="text-md mb-2">Accéder au cabinet dentaire</h2>

                    <div class="divider mx-auto my-4"></div>
                    <br>
                </div>
<section class="features">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="feature-block d-lg-flex">
          <div class="feature-item mb-5 mb-lg-0">
            <div class="feature-icon mb-4">
              <i class="icofont-car-alt-3"></i>
            </div>
            <span>Service en ligne</span>
            <h4 class="mb-3">Se garer autour du cabinet</h4>
            <p class="mb-4">Le parking le plus proche est situé derrière le gymnase (400 places)

La rue Pierre et Marie Curie est parralèlle à la rue du port et dispose d'une centaine de place en zone bleue (stationnement gratuit et limité à 1h30).</p>

          </div>

          <div class="feature-item mb-5 mb-lg-0">
            <div class="feature-icon mb-4">
              <i class="icofont-ui-clock"></i>
            </div>
            <span>Uniquement sur Rendez-Vous</span>
            <h4 class="mb-3">Horaires d'ouverture</h4>
            <ul class="w-hours list-unstyled">
                        <li class="d-flex justify-content-between">Lu-Ma-Me-Ve : <span>8:00-12:30|14h00-18h30</span></li>
                        <li class="d-flex justify-content-between">Jeudi : <span>8:00 - 12:30</span></li>
                        <li class="d-flex justify-content-between">Sa - Dim : <span style = "color:red;">fermé</span></li>
                    </ul>
          </div>

          <div class="feature-item mb-5 mb-lg-0">
            <div class="feature-icon mb-4">
              <i class="icofont-support"></i>
            </div>
            <span>Nous contacter par téléphone</span>
            <h4 class="mb-3">+33 4 94 01 91 01</h4>
            <p>En cas d'urgence, veuillez consulter notre page dédiée.</p>
            <a href="appoinment.html" class="btn btn-main btn-round-full">Urgence</a>

            <p class="mb-4"><br><strong>Adresse :</strong> 130 Rue du port Résidence Le Beau Rivage 1er étage 83240 Cavalaire</p>

          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<br>

<div class="google-map ">
    <div id="map"></div>
</div>
</div>
</div>
</div>
</section>

app/views/pages/drgrard.html.erb
<section class="page-title bg-1">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="block text-center">

          <h1 class="text-capitalize mb-5 text-lg">Docteur GRARD Valéry</h1>

          <!-- <ul class="list-inline breadcumb-nav">
            <li class="list-inline-item"><a href="index.html" class="text-white">Home</a></li>
            <li class="list-inline-item"><span class="text-white">/</span></li>
            <li class="list-inline-item"><a href="#" class="text-white-50">Doctor Details</a></li>
          </ul> -->
        </div>
      </div>
    </div>
  </div>
</section>


<section class="section doctor-single">
  <div class="container">
    <div class="row">
      <div class="col-lg-4 col-md-6">
        <div class="doctor-img-block">
          <img src="../assets/AvatarValery.png" alt="" class="img-fluid w-100">

          <div class="info-block mt-4">
            <h4 class="mb-0">Dr Valery GRARD</h4>
            <p>Chirurgien-dentiste</p>

            <%#<ul class="list-inline mt-4 doctor-social-links">
              <li class="list-inline-item"><a href="#"><i class="icofont-facebook"></i></a></li>
              <li class="list-inline-item"><a href="#"><i class="icofont-twitter"></i></a></li>
              <li class="list-inline-item"><a href="#"><i class="icofont-skype"></i></a></li>
              <li class="list-inline-item"><a href="#"><i class="icofont-linkedin"></i></a></li>
              <li class="list-inline-item"><a href="#"><i class="icofont-pinterest"></i></a></li>
            </ul>%>
          </div>
        </div>
      </div>

      <div class="col-lg-8 col-md-6">
        <div class="doctor-details mt-4 mt-lg-0">
          <h2 class="text-md">Bienvenue</h2>
          <div class="divider my-4"></div>
          <p>Le Docteur GRARD, chirurgien-dentiste à Cavalaire, proche de St Tropez et Lavandou, est heureuse de vous accueillir sur le site Internet de son cabinet.<br>

 La dentisterie moderne, et les progrès de la profession permettent au Dr GRARD de vous accompagner quotidiennement pour une bonne hygiène dentaire, des soins spécifiques en implantologie, parfaitement adaptés avec le souci permanent de la meilleure esthétique dentaire.<br>



Le docteur GRARD pratique  une Dentisterie générale et plus particulierement la parodontologie, l'implantologie et la chirurgie buccale. Par ailleurs, nous assurons vos soins en Endodontie, vos eclaircissements de dents au cabinet, mais aussi  la pose de prothèses fixes et amovibles.</p>

          <a href="<%=pages_contact_path%>" class="btn btn-main-2 btn-round-full mt-3">Contacter le cabinet dentaire<i class="icofont-simple-right ml-2  "></i></a>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="section doctor-qualification gray-bg">
  <div class="container">
    <div class="row">
      <div class="col-lg-6">
        <div class="section-title">
          <h3>Les qualifications du Dr Grard Valéry</h3>
          <div class="divider my-4"></div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-6">
        <div class="edu-block mb-5">
          <span class="h6 text-muted">1994</span>
          <h4 class="mb-3 title-color">Conseil de l'ordre des chirurgiens-dentistes</h4>
          <p>Premier prix au concours de déontologie du conseil de l’ordre des chirurgiens-dentistes</p>
        </div>

        <div class="edu-block">
          <span class="h6 text-muted">1995</span>
          <h4 class="mb-3 title-color">Faculté d’odontologie Université de la méditerranée Aix-Marseille II</h4>
          <p>Diplôme d’État de docteur en chirurgie-dentaire<br>Diplôme de maitrise de sciences biologiques et médicales </p>
        </div>
      </div>

      <div class="col-lg-6">
        <div class="edu-block mb-5">
          <span class="h6 text-muted">1996 – 1997</span>
          <h4 class="mb-3 title-color">Faculté d’odontologie Université de la méditerranée Aix-Marseille II</h4>
          <p>Diplôme universitaire de parodontologie<br>Certificat d’études supérieures de prothèse scellée<br>Certificat d’études supérieures de parodontologie</p>
        </div>

        <div class="edu-block">
          <span class="h6 text-muted">1998 - 1999</span>
          <h4 class="mb-3 title-color">Faculté d’odontologie Université de la méditerranée Aix-Marseille II</h4>
          <p>Diplôme universitaire d’anthropologie odontologie médico-légale </p>
        </div>
      </div>


      <div class="col-lg-6">
        <div class="edu-block mb-5">
          <span class="h6 text-muted">2000 - 2003</span>
          <h4 class="mb-3 title-color">Faculté d’odontologie Université de la méditerranée Aix-Marseille II</h4>
          <p>Diplôme universitaire d’implantologie </p>
        </div>

        <div class="edu-block">
          <span class="h6 text-muted">2015</span>
          <h4 class="mb-3 title-color">Association Universitaire d'Implantologie</h4>
          <p>Certificat de compétence clinique en chirurgie dentaire lasers assistée </p>
        </div>
      </div>


      <div class="col-lg-6">
        <div class="edu-block mb-5">
          <span class="h6 text-muted">2018</span>
          <h4 class="mb-3 title-color">Université de Nice</h4>
          <p>Attestation d’études universitaires en imagerie 3D </p>
        </div>


      </div>




    </div>
  </div>
</section>


<section class="section doctor-skills">
  <div class="container">
    <div class="row">
      <div class="col-lg-4">
        <h3>En résumé</h3>
        <div class="divider my-4"></div>
        <p>Le docteur GRARD pratique  une Dentisterie générale et plus particulierement la parodontologie, l'implantologie et la chirurgie buccale. Par ailleurs, elle assure vos soins en Endodontie, vos eclaircissements de dents au cabinet, mais aussi la pose de prothèses fixes et amovibles.</p>
      </div>
      <div class="col-lg-4">
        <div class="skill-list">
          <h5 class="mb-4">Ses compétences</h5>
          <ul class="list-unstyled department-service">
            <li><i class="icofont-check mr-2"></i>Parodontologie</li>
            <li><i class="icofont-check mr-2"></i>Implantologie</li>
            <li><i class="icofont-check mr-2"></i>Chirurgie buccale</li>
            <li><i class="icofont-check mr-2"></i>Esthétique</li>
            <li><i class="icofont-check mr-2"></i>Prothèses fixes et amovibles</li>
            <li><i class="icofont-check mr-2"></i>Soins conservateurs</li>
          </ul>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="sidebar-widget  gray-bg p-4">
          <h5 class="mb-4">Infos du cabinet dentaire</h5>

          <ul class="list-unstyled lh-35">
            <li class="d-flex justify-content-between align-items-center">
              <a href="#">Lu-Ma-Me-Ve :</a>
              <span>8:00-12:30|14h00-18h30</span>
            </li>
            <li class="d-flex justify-content-between align-items-center">
              <a href="#">Jeudi :</a>
              <span>8:00 - 12:30</span>
            </li>
            <li class="d-flex justify-content-between align-items-center">
              <a href="#">Sa - Dim :</a>
              <span style = "color:red;">Fermé</span>
            </li>
          </ul>

          <div class="sidebar-contatct-info mt-4">
            <p class="mb-0">Vous voulez nous contacter?</p>
            <h3 class="text-color-2">+33 4 94 01 91 01</h3>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/shared/_footer.html.erb
<footer class="footer section gray-bg">
  <div class="container">
    <div class="row">
      <div class="col-lg-4 mr-auto col-sm-6">
        <div class="widget mb-5 mb-lg-0">
          <div class="logo mb-4">
            <img style="width:200px;" src="../assets/logo.png" alt="" class="img-fluid">
          </div>
          <p>Cabinet dentaire Cavalaire - St Tropez - Lavandou<br>130 Rue du port Résidence Le Beau Rivage<br>1er etage<br>83240 Cavalaire</p>

          <ul class="list-inline footer-socials mt-4">
            <li class="list-inline-item"><a href="https://www.facebook.com/themefisher"><i class="icofont-facebook"></i></a></li>
            <li class="list-inline-item"><a href="https://twitter.com/themefisher"><i class="icofont-twitter"></i></a></li>
            <li class="list-inline-item"><a href="https://www.pinterest.com/themefisher/"><i class="icofont-linkedin"></i></a></li>
          </ul>
        </div>
      </div>



      <div class="col-lg-3 col-md-6 col-sm-6">
        <div class="widget mb-5 mb-lg-0">
          <h4 class="text-capitalize mb-3">En savoir plus</h4>
          <div class="divider mb-4"></div>

          <ul class="list-unstyled footer-menu lh-35">

            <li><a href="#">Mentions légales</a></li>

            <li><a href="#">Code de déontologie dentaire</a></li>
            <li><a href="http://www.ordre-chirurgiens-dentistes.fr" target="_blank">Ordre national des chirurgiens-dentistes</a></li>
            <li><a href="http://www.ordre-chirurgiens-dentistes.fr/annuaire/" target="_blank">Annuaire des chirurgiens-dentistes</a></li>

          </ul>
        </div>
      </div>

      <div class="col-lg-3 col-md-6 col-sm-6">
        <div class="widget widget-contact mb-5 mb-lg-0">
          <h4 class="text-capitalize mb-3">Restons en contact</h4>
          <div class="divider mb-4"></div>

          <div class="footer-contact-block mb-4">
            <div class="icon d-flex align-items-center">
              <i class="icofont-email mr-3"></i>
              <span class="h6 mb-0">Par E-mail</span>
            </div>
            <h4 class="mt-2"><a href="tel:+23-345-67890">Support@email.com</a></h4>
          </div>

          <div class="footer-contact-block">
            <div class="icon d-flex align-items-center">
              <i class="icofont-support mr-3"></i>
              <span class="h6 mb-0">Par Téléphone</span>
            </div>
            <h4 class="mt-2"><a href="tel:+23-345-67890">+33 4 94 01 91 01</a></h4>
          </div>
        </div>
      </div>
    </div>

    <div class="footer-btm py-4 mt-5">
      <div class="row align-items-center justify-content-between">
        <div class="col-lg-6">
          <div >
             Co-Web Dentaire <span class="text-color">STAUMONT Antoine</span>
          </div>
        </div>
        <div class="col-lg-6">
          <div class="subscribe-form text-lg-right mt-5 mt-lg-0">
            <form action="#" class="subscribe">
              <input type="text" class="form-control" placeholder="Your Email address">
              <a href="#" class="btn btn-main-2 btn-round-full">Subscribe</a>
            </form>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-lg-4">
          <a class="backtop js-scroll-trigger" href="#top">
            <i class="icofont-long-arrow-up"></i>
          </a>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<header>
  <div class="header-top-bar">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-lg-6">
          <ul class="top-bar-info list-inline-item pl-0 mb-0">
            <li class="list-inline-item"><a href="mailto:support@gmail.com"><i class="icofont-support-faq mr-2"></i>support@novena.com</a></li>
            <li class="list-inline-item"><i class="icofont-location-pin mr-2"></i>130 Rue du port Résidence Le Beau Rivage 1er etage 83240 Cavalaire</li>
          </ul>
        </div>
        <div class="col-lg-6">
          <div class="text-lg-right top-right-bar mt-2 mt-lg-0">
            <a href="tel:+23-345-67890" >
              <span>Nous Contacter : </span>
              <span class="h4">+33 4 94 01 91 01</span>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <nav class="navbar navbar-expand-lg navigation" id="navbar">
    <div class="container">
       <a class="navbar-brand" href="index.html">
          <img src="../assets/logo.png" style="width:150px;" alt="" class="img-fluid">
        </a>

        <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarmain" aria-controls="navbarmain" aria-expanded="false" aria-label="Toggle navigation">
      <span class="icofont-navigation-menu"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarmain">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
        <a class="nav-link" href="<%= root_path%>">Accueil</a>
        </li>
         <li class="nav-item"><a class="nav-link" href="<%=pages_cabinet_path%>">Le cabinet</a></li>
          <li class="nav-item"><a class="nav-link" href="<%=pages_drgrard_path%>">Dr Grard</a></li>

          <li class="nav-item"><a class="nav-link" href="<%=pages_services_path%>">Nos services</a></li>


         <li class="nav-item"><a class="nav-link" href="<%=pages_conseils_path%>">Nos Conseils</a></li>



         <li class="nav-item"><a class="nav-link" href="<%=pages_contact_path%>">Nous Contacter</a></li>
      </ul>
      </div>
    </div>
  </nav>
</header>